title: Quantum & Society

plugins:
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]

defaults:
  - scope:
      path: ''
      type: pages
    values:
      permalink: /:title